import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import AboutSection from '../components/AboutSection';
import HeroSection from '../components/HeroSection';
import NavBar from '../components/NavBar';
import ProjectSection from '../components/ProjectSection';

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className='w-full min-h-screen overflow-x-auto '>
				<div className='wrapper flex flex-col space-y-12'>
					<NavBar />
					<HeroSection />
					<AboutSection />
					<ProjectSection />
				</div>
			</main>
		</>
	);
};

export default Home;
