import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import NavBar from '../components/NavBar';

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className='w-full min-h-screen overflow-scroll '>
				<div className='wrapper'>
					<NavBar />
				</div>
			</main>
		</>
	);
};

export default Home;
